// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKx91M7dIDH1Pj4fgQ2xcoyVPR-Ngfohw',
    appId: '1:1025326442181:web:8b92c299a15c2c3bdf32ac',
    messagingSenderId: '1025326442181',
    projectId: 'foodapp-4b3cf',
    authDomain: 'foodapp-4b3cf.firebaseapp.com',
    storageBucket: 'foodapp-4b3cf.appspot.com',
    measurementId: 'G-0G0NTEGE27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH36LVnMJjsPWJWG6iZ1bae8d9NkWLdvw',
    appId: '1:1025326442181:android:d0c67ba673eca093df32ac',
    messagingSenderId: '1025326442181',
    projectId: 'foodapp-4b3cf',
    storageBucket: 'foodapp-4b3cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVkmhLrrRjgrkujmhbjinhPNT66nNC-7E',
    appId: '1:1025326442181:ios:e0f860c36fd0184adf32ac',
    messagingSenderId: '1025326442181',
    projectId: 'foodapp-4b3cf',
    storageBucket: 'foodapp-4b3cf.appspot.com',
    iosBundleId: 'com.example.foodapp',
  );
}
