// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeCj6esdWrcUbQ8cE1Z098qO9YxH3ZDmE',
    appId: '1:242740971205:web:f402f0e201a8a5e4d052ac',
    messagingSenderId: '242740971205',
    projectId: 'foodapp-cd59b',
    authDomain: 'foodapp-cd59b.firebaseapp.com',
    storageBucket: 'foodapp-cd59b.appspot.com',
    measurementId: 'G-PYJYE1LK01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_ZNZaDxa8dX7ejrdPkDqQQpC-75faLtw',
    appId: '1:242740971205:android:e32baa1ae24e27b6d052ac',
    messagingSenderId: '242740971205',
    projectId: 'foodapp-cd59b',
    storageBucket: 'foodapp-cd59b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr-OLh1WTxNuyUnZ3NdoS-pvO7ge5kqSs',
    appId: '1:242740971205:ios:4d2509feb0e11a00d052ac',
    messagingSenderId: '242740971205',
    projectId: 'foodapp-cd59b',
    storageBucket: 'foodapp-cd59b.appspot.com',
    iosBundleId: 'com.example.foodapp',
  );
}
